### PR TITLE
decouple requirements files in lieu of assembling via tox config 

### PR DESCRIPTION
**Pull request by tomkralidis**
# Overview
Unchains `requirements-dev.txt` file and explicitly specify in `tox.ini` instead.

# Related Issue / Discussion
#521, #497 

# Additional Information

# Contributions and Licensing

(as per https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [ ] I'd like to contribute [feature X|bugfix Y|docs|something else] to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.
- [x] I have already previously agreed to the pycsw Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by tomkralidis** [comment]
Thanks @ricardogsilva. I'm good with your proposal. Before I make changes to this PR, not it also currently addresses #497. Any suggestions with the proposed update to handle non-PG dev envs?

**Comment by ricardogsilva** [comment]
Regarding #497 I think the solution is a refactor to 

https://github.com/geopython/pycsw/blob/master/tests/functionaltests/conftest.py

in order to load the `psycopg2` module lazily, and only if needed.

**Comment by tomkralidis** [comment]
@ricardogsilva ok will cover the PG issue in another PR then.

This PR has been fixed and rebased for your review.

**Comment by tomkralidis** [comment]
@ricardogsilva: done/rebased.  `mock` is included to take into account building docs on Python 2 or 3 envs (see https://github.com/geopython/pycsw/blob/master/docs/conf.py#L44-L47 and https://github.com/geopython/pycsw/blob/master/docs/conf.py#L336-L342

**Comment by ricardogsilva** [comment]
merged - Great! Thanks a lot @tomkralidis

**Pull request merged**
