### PR TITLE
Travis-CI container build

### PR DESCRIPTION
**Pull request by ocefpaf**
Use Travis-CI container build.

### CODE REVIEW

**Comment by kalxas** [comment]
@ocefpaf can you please add yourself here, accepting the contributor and license agreement?
https://github.com/geopython/pycsw/issues/312

**Comment by ocefpaf** [comment]
> @ocefpaf can you please add yourself here, accepting the contributor and license agreement?

Done.  Thanks @kalxas.

**Comment by kalxas** [comment]
Thanks.

**Comment by tomkralidis** [comment]
Minor note: @ocefpaf could have also given agreement as part of this PR.

Regardless, thanks @ocefpaf!

**Pull request merged**
