### PR TITLE
codecov integration

### PR DESCRIPTION
**Pull request by ricardogsilva**
# Overview

This PR brings integration with the [codecov](https://codecov.io/) service.

The general idea is that our CI service will run the tests with `coverage.py` and afterwards upload coverage results to codecov. This involves running parallel coverage and then combining everything in the end.
It will be using the [new multi-stage capabilities in Travis](https://docs.travis-ci.com/user/build-stages/) (which are awesome by the way).

# Related Issue / Discussion

See #511 

# Additional Information

# Contributions and Licensing

(as per https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.
- [x] I have already previously agreed to the pycsw Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by ricardogsilva** [comment]
@tomkralidis 
In order to complete this I'm going to need you, as github admin to enable pycsw integration with codecov. I'm not blocked for now, as I'm testing against my own fork. Let's meet on gitter sometime this week or next (at your convenience) and I can walk you through it if needed.

**Comment by tomkralidis** [comment]
@ricardogsilva I've enabled codecov is integration for pycsw. Do we need to close/reopen this PR?

**Comment by tomkralidis** [comment]
Reopening, travis ci running.

**Comment by ricardogsilva** [comment]
@tomkralidis the work is not finished yet.

I'll ask for review when it seems ready to merge

**Comment by ricardogsilva** [comment]
@tomkralidis @kalxas 
I think this is done.

As you can see (from this PR) we will now have a *codecov bot* analyzing PRs and indicating code coverage status. In this case, since it is the first time that we are adding codecov it cannot compute the difference between the PR and the master branch, and that is why it is showing a failed check. Other codecov functionality is not working very well yet, due to the same problem. This will be fixed once we merge codecov integration into master.

Later on we can [configure the codecov settings](https://docs.codecov.io/docs/coverage-configuration) by adding a `.codecov.yml` file to the repo.

I think I won't be adding a coverage badge to the `README` yet because with the default codecov settings it would have a red color, since our global coverage is at 56% and the badge only turns green from 70% up. We could decide what a nice value for green would be, configure codecov appropriately and then add a badge to the README. What do you think? 

Another thing implemented in this PR is usage of Travis' build stages. If you check Travis you'll see that we now have a `unit-test` and an `integration-test` stage. Stages run sequentially (first unit tests then integration tests). If one stage fails the following stages don't run. Inside each stage we have three 3 concurrent jobs, one for each python env (2.7, 3.4, 3.5). Each job of the same stage runs in parallel.

**Comment by tomkralidis** [comment]
cc @kalxas 

Thanks @ricardogsilva.  Should we keep with 70% code coverage with the goal to improve or lower our baseline?  Thoughts?

I like the build stages and the early failure approach the provide.

+1 for merge pending decision on coverage threshold value.

**Comment by kalxas** [comment]
Thanks @ricardogsilva 
+1 for the proposed changes
Lets not add the codecov badge yet.

**Comment by ricardogsilva** [comment]
Let's discuss the threshold for green coverage on the next dev meeting

**Comment by tomkralidis** [comment]
+1. Added to [draft agenda](https://github.com/geopython/pycsw/wiki/Meetings-2017-06-12#agenda-draft).

**Comment by ricardogsilva** [comment]
FYI, now that is has been merged you can go to 

https://codecov.io/gh/geopython/pycsw

and see a detailed view on the coverage of each file, with line by line visualization of code covered (green), missed (red) and partially covered (yellow)

**Pull request merged**
