### PR TITLE
Support multiple formats and crs

### PR DESCRIPTION
**Pull request by Rastopapola**
@tomkralidis That's basically my first ever github pull request. I only worked with gitlab or gitea until now. Please take a look if I missed anything.

# Overview
* adds support for comma separated formats ('Format1,Format2,Format3')
* adds support for comma separated spatial reference systems ('crs1,crs2,crs3')

# Related Issue / Discussion
#617 

# Additional Information
* multiple formats and crs can be strings containing just the required data **or** containing multiple values, comma separated
* multiple values will be mapped to multiple elements in the CSW response

# Contributions and Licensing

(as per https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [x] I'd like to contribute this feature to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.
- [ ] I have already previously agreed to the pycsw Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by Rastopapola** [comment]
@tomkralidis I'm sorry, there was a stupid bug I pushed in the first commit. Checks have been passed fine now.

**Comment by tomkralidis** [comment]
Thanks @Rastopapola , some comments:

1. we'll need docs added to the new behaviour of the `pycsw:Format` and `pycsw:CRS` fields in https://docs.pycsw.org/en/latest/administration.html#existing-repository-requirements
2. the PR supports the "existing database" workflow.  I think we also need to support ingest.  This means demonstrating that pycsw can ingest a sample Dublin Core document with multiple fields, store it into the core model, and finally be able to output accordingly
3. it would be valuable to have the tests updated based on 2.

**Comment by Rastopapola** [comment]
>the PR supports the "existing database" workflow. I think we also need to support ingest. This means demonstrating that pycsw can ingest a sample Dublin Core document with multiple fields, store it into the core model, and finally be able to output accordingly

Yes, I see. I will take care of this tomorrow.

**Comment by Rastopapola** [comment]
News on this PR can be found [here](https://github.com/geopython/pycsw/issues/617#issuecomment-630799725)

**Pull request closed without merging**
