### PR TITLE
Util unit tests

### PR DESCRIPTION
**Pull request by ricardogsilva**
# Overview

This Pull Request adds some refactoring to stuff in `pycsw.core.util` and also some unit tests to go along with the changes.

There are quite a few changes here:

* some functions have been moved to the modules where they are used;
* some were deleted because they were not used anywhere
* most of them were refactored with the intent to make them more readable and thus easier to maintain
* all functions that have been changed now have unit tests. These are in `tests/unittests`
* `.travis.yml` has been updated in order to run the unit tests first and then the functional ones. This was made to speed up CI in case of failures. The unit tests run much faster, so it makes sense to run them first and fail as fast as possible
* `docs/testing.rst` has been updated with some information on how to run unit tests

# Related Issue / Discussion

This PR is related to [RFC8](http://pycsw.org/development/rfc/rfc-8.html) because it is expanding on the previous integration of py.test that featured only functional tests. This establishes a foundation for adding unit tests and shows how they integrate into py.test as well. 

# Additional Information

# Contributions and Licensing

(as per https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.
- [x] I have already previously agreed to the pycsw Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by ricardogsilva** [comment]
I see that there are some conflicts (thats what I get for not mergin master while working...) I'll fix these and then we can move along with code review

**Comment by ricardogsilva** [comment]
OK, conflicts resolved now

**Comment by tomkralidis** [comment]
Thanks @ricardogsilva!  Great to see the unit tests. +1 to merge.

**Comment by kalxas** [comment]
Thanks @ricardogsilva

**Pull request merged**
