### PR TITLE
[WIP] pin libxml2 at 2.9.1

### PR DESCRIPTION
**Pull request by tomkralidis**
# Overview

**DO NOT MERGE**

Test for libxml2 2.9.1 travis pinning.  Looks like libxml2 2.9.4 introduces XML validation errors.
# Related Issue / Discussion
# Additional Information
# Contributions and Licensing

(as per https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst#contributions-and-licensing)
- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.
- [ ] I have already previously agreed to the pycsw Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by tomkralidis** [comment]
cc @kalxas 

Looks like is an lxml issue.  3.6.1 works, 3.6.4 breaks.

**Comment by tomkralidis** [comment]
On second thought, more testing:

- lxml 3.6.1 && libxml2 2.9.1 passes
- lxml 3.6.2 && libxml2 2.9.1 passes
- lxml 3.6.3 && libxml2 2.9.4 FAILS with said validation error
- lxml 3.6.4 && libxml2 2.9.4 FAILS with said validation error

**Comment by ricardogsilva** [comment]
It would be great if we could bump the version of `lxml` to 3.6.3 or higher. According to [this thread on stackoverflow](http://stackoverflow.com/a/39064329), and I've also tested it myself on ubuntu 16.04, `lxml` is now providing wheels (AKA binary downloads) on pypi. This would mean that installing lxml would be a lot faster on Travis (and everywhere else too). It would also mean that installing pycsw would be faster and with fewer external dependencies (no need for libxml2-dev and libxslt1-dev anymore).

**Comment by tomkralidis** [comment]
cc @kalxas 

@ricardogsilva not sure about this one given #454.  @kalxas?

**Comment by kalxas** [comment]
We have to make sure that other distributions also have this version available, not just Pypi.

**Comment by tomkralidis** [comment]
Given #454 it looks like there has not been any releases of libxml2 since this bug was addressed?

**Comment by ricardogsilva** [comment]
@tomkralidis @kalxas 
FYI, [libxml2 has a new release out, version 2.9.5](https://mail.gnome.org/archives/xml/2017-September/msg00000.html). Perhaps this will fixes the long standing validation issues?

**Comment by kalxas** [comment]
we have to test :)

**Comment by tomkralidis** [comment]
Closing.  Looks like deploys are using recent libxml2 builds.

**Pull request closed without merging**
