### PR TITLE
Docker documentation update

### PR DESCRIPTION
**Pull request by ricardogsilva**
# Overview

This PR adds documentation on how to use pycsw's official Docker image, which has recently been merged with #534 

# Related Issue / Discussion

#530  
#534 

# Additional Information

# Contributions and Licensing

(as per https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.
- [x] I have already previously agreed to the pycsw Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by ricardogsilva** [comment]
@kalxas 

This is now ready for review. However, it is dependent on merging #548, as some of the docs already mention the improvements of the other PR.

**Comment by ricardogsilva** [comment]
I've requested a review also from @tomkralidis as he seems to be in charge of docs ;)

**Comment by kalxas** [comment]
thanks @ricardogsilva I will review and merge #548 first

**Comment by tomkralidis** [comment]
@ricardogsilva really nice work here.  I see you made the docker docs as its own page that is included by `installation.rst`.  Should the Docker section simply be in `installation.rst` or should we have the docker page as a first order navigation (parallel to `installation.rst`)? I'd prefer the former given it covers both installing and deployment?

**Comment by tomkralidis** [comment]
Sorry I meant I prefer the latter.

**Comment by ricardogsilva** [comment]
@tomkralidis I wasn't sure where to put these new docs. Ended up putting them under `installation` but was kind of hoping for some direction. I'll move them to their own section then. Where would they fit in? Right after installation? After administration?

**Comment by tomkralidis** [comment]
@ricardogsilva let's go with right after installation?

**Comment by ricardogsilva** [comment]
OK, I'll update

**Comment by ricardogsilva** [comment]
@tomkralidis 

I've made the change, ready for re-review

**Comment by tomkralidis** [comment]
Thanks @ricardogsilva!

**Pull request merged**
