### PR TITLE
Added a build badge to the README and also renamed it from .txt to .rst

### PR DESCRIPTION
**Pull request by ricardogsilva**
# Overview

This PR adds a build badge to the README in order to show off our CI state. It also renames the file from `README.txt` to `README.rst`, which seems more explicit.

# Related Issue / Discussion

See #512 

# Contributions and Licensing

(as per https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.
- [x] I have already previously agreed to the pycsw Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by kalxas** [comment]
Renaming readme.txt caused a break in the setup.py for GeoNode recently.

**Comment by kalxas** [comment]
ok, setup.py was covered.
Thanks.

**Comment by tomkralidis** [comment]
@ricardogsilva can you fix/rebase the merge conflicts here? I will merge thereafter.

**Comment by ricardogsilva** [comment]
Yes, I'll fix the conflicts and then we can merge

**Comment by ricardogsilva** [comment]
@tomkralidis 
I've fixed the conflict. Shoudl be good to merge, pending your review.

**Comment by tomkralidis** [comment]
@ricardogsilva can you fix/rebase? Looks like some earlier commits are being pushed again.

**Comment by ricardogsilva** [comment]
grrr, there's something with this git rebase workflow that fights with my brain all the time.

yeah I'll fix it later then,, sorry for the noise

**Comment by tomkralidis** [comment]
Here's what usually works for me (untested) assuming you keep a backup of this branch on disk while fixing.

```bash
git checkout 502-add-a-build-badge-to-the-readme
git remote add upstream https://github.com/geopython/pycsw.git
git fetch upstream
git reset --hard upstream/master
# now you are at parity with upstream master
# rename/add badge to README.rst, make changes to MANIFEST.in and setup.py
git commit -m 'your-commit-message'
git push -f origin 502-add-a-build-badge-to-the-readme
```

**Comment by ricardogsilva** [comment]
@tomkralidis thanks for the tip on cleaning up the commit history. Worked like a charm!
This is ready for review again

**Comment by tomkralidis** [comment]
thanks @ricardogsilva!

**Pull request merged**
