### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by ocefpaf**
See https://github.com/geopython/pycsw/pull/376

### CODE REVIEW

**Comment by ocefpaf** [comment]
Hopefully I rebased this correctly.  However, it would be best to merge this into the py3k branch or to close this PR.  Otherwise it will be a burden to maintain this updated.

**Comment by tomkralidis** [comment]
Hi @ocefpaf backported already in 7ddfc52f114bc316c8dc9b2ff4483eeb24427753

**Comment by ocefpaf** [comment]
Yes, but this is the py3k branch with un-merged py3k support.  So I guess this PR is no longer relevant.

However, I would reference it who whomever start working on py3k support again.

**Comment by tomkralidis** [comment]
@ocefpaf ah, ok.  How is this different than https://github.com/geopython/pycsw/tree/py3k ?

**Comment by ocefpaf** [comment]
When you created the py3k branch it was based on master.  I redirect my py3k PR from master to the py3k branch you created.  You can see above to which branch the PR is pointing to:

> geopython:py3k from ocefpaf:py3k

You can see in the "Files changed" tab all the differences.

Also note that your [backport](https://github.com/ocefpaf/pycsw/commit/978d0b7c78a38b1ecaaa57e79a94d0410b3f5cde), now that I rebased the PR, is part of the commits here.

**Comment by kalxas** [comment]
Since the PR is redirected we can merge

**Pull request merged**
