### PR TITLE
Remove packaging

### PR DESCRIPTION
**Pull request by kalxas**
# Overview
Fixes issue #442 

# Related Issue / Discussion

# Additional Information

# Contributions and Licensing

(as per https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [ ] I'd like to contribute [feature X|bugfix Y|docs|something else] to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.
- [X] I have already previously agreed to the pycsw Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by tomkralidis** [comment]
Can we add README files with info on Debian and OpenSUSE canonical locations?

**Comment by kalxas** [comment]
I don't see the point to do that, we should just update the docs to inform users where to find pycsw packaged for them.

**Comment by kalxas** [comment]
We are still missing a reference to DebianGIS in the installation doc, but since pycsw did not reach a stable Debian release yet, I did not add that reference yet

https://packages.debian.org/search?keywords=python-pycsw

How should we proceed? Add a reference to DebianGIS even if it points to Debian unstable?

**Comment by tomkralidis** [comment]
+1 good idea.

**Pull request merged**
