### PR TITLE
Issue 556

### PR DESCRIPTION
**Pull request by rogie-bas**
# Overview

The value of the `numberOfRecordsReturned` attribute returned with a GetRecords request was incorrect if the number of record left in the catalogue is less than the `maxrecord` parameter passed with the request, but the number of `matched` records is greater than `maxrecords`.  This can happen if the `startposition` parameter specified with the GetRecords request is close to the number of matched records, such that `(startposition+maxrecords) > matched`.

The csw2.py and csw3.py files both had code which allowed: `numberOfRecordsReturned=maxrecords` if `(startposition+maxrecords) > matched`

With functional testing, the changes also highlighted that one of the functional tests expected incorrect reponse XML.  The test, `default_post_GetRecords-end`, has had its expected XML modified to reflect the correct expected attribute value. 

Also, when `maxRecords=0`, the behaviour is the same as `resultType=hits` and no records are returned.  In this case, `nextRecord` and `numberOfRecordsReturned` should be returned as 0.  Making sure this happens also impacted a CITE functional test: `post_0c976d98-c896-4b10-b1fe-a22ef50434e7.xml` which specifies `maxRecords=0`, but expected `nextRecord=1`.  This has been amended to expect `nextRecord=0`.

# Related Issue / Discussion

There are no unit tests for this piece of the code.  Might it be useful to create some?

The way that the code determines the number of returned records is perhaps a little reckless?  It would probably be safer to count the number of records, then assign that number to the attribute, rather than do the calculation based on input parameters and the total number of matched records.  This might be a bigger piece of work, however.  I have not investigated how this approach could be implemented.

# Additional Information

# Contributions and Licensing

(as per https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

I'd like to contribute this bugfix, relating to the reported value of numberOfRecordsReturned during GetReocrds requests, to the pycsw project. I confirm that my contributions to pycsw will be compatible with the pycsw licence guidelines at the time of contribution.

### CODE REVIEW

**Comment by tomkralidis** [comment]
@rjaduthie thanks for the fixes.  When trying this against the OGC CITE tests I am getting failure:

```
      The response to a GetRecords request that specifies maxRecords=&quot;0&quot; must 
      not include any results.
```

Request
```xml
<csw:GetRecords xmlns="http://www.occamlab.com/ctl"
                xmlns:csw="http://www.opengis.net/cat/csw/2.0.2"
                xmlns:ctl="http://www.occamlab.com/ctl"
                xmlns:dc="http://purl.org/dc/elements/1.1/"
                xmlns:dct="http://purl.org/dc/terms/"
                xmlns:gen="java:com.occamlab.te.Generator"
                xmlns:gml="http://www.opengis.net/gml"
                xmlns:ogc="http://www.opengis.net/ogc"
                xmlns:ows="http://www.opengis.net/ows"
                xmlns:p="http://teamengine.sourceforge.net/parsers"
                xmlns:parsers="http://www.occamlab.com/te/parsers"
                xmlns:saxon="http://saxon.sf.net/"
                xmlns:te="http://www.occamlab.com/te"
                xmlns:tec="java:com.occamlab.te.TECore"
                xmlns:tems="java:com.occamlab.te.web.MonitorServlet"
                xmlns:xi="http://www.w3.org/2001/XInclude"
                xmlns:xlink="http://www.w3.org/1999/xlink"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                maxRecords="0"
                resultType="results"
                service="CSW"
                version="2.0.2">
   <csw:Query typeNames="csw:Record">
      <csw:ElementName>dc:identifier</csw:ElementName>
      <csw:ElementName>ows:BoundingBox</csw:ElementName>
      <csw:Constraint version="1.1.0">
         <ogc:Filter>
            <ogc:Not>
               <ogc:BBOX>
                  <ogc:PropertyName>ows:BoundingBox</ogc:PropertyName>
                  <gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11:4326">
                     <gml:lowerCorner>60.0 12.0</gml:lowerCorner>
                     <gml:upperCorner>70.0 20.0</gml:upperCorner>
                  </gml:Envelope>
               </ogc:BBOX>
            </ogc:Not>
         </ogc:Filter>
      </csw:Constraint>
   </csw:Query>
</csw:GetRecords>
```

Response
```xml
      <csw:GetRecordsResponse xmlns:csw="http://www.opengis.net/cat/csw/2.0.2"
                        xmlns:dc="http://purl.org/dc/elements/1.1/"
                        xmlns:dct="http://purl.org/dc/terms/"
                        xmlns:gmd="http://www.isotc211.org/2005/gmd"
                        xmlns:gml="http://www.opengis.net/gml"
                        xmlns:ows="http://www.opengis.net/ows"
                        xmlns:xs="http://www.w3.org/2001/XMLSchema"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        version="2.0.2"
                        xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2 http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd">
  <csw:SearchStatus timestamp="2017-12-07T11:30:59Z"/>
  <csw:SearchResults nextRecord="0" numberOfRecordsMatched="11" numberOfRecordsReturned="0"
                      recordSchema="http://www.opengis.net/cat/csw/2.0.2"/>
   <!--Response received in [501] milliseconds--></csw:GetRecordsResponse>
```

Message from CITE:
```
   [FAILURE] Expected csw:SearchResults/@nextRecord = 1.
```

More info on how we test against CITE can be found at https://github.com/geopython/pycsw/wiki/OGC-CITE-Compliance.

**Comment by rjaduthie** [comment]
I have had a response from the CITE forum mailing list.  They ask whether the test that fails is "csw-2.0.2-GetRecords-tc23.1".  If it is then the "Expected csw:SearchResults/@nextRecord = 1" might need a review.

I am unable to easily do a CITE test myself, although with a little time I could probably set up a externally accessible PyCSW server using the development source.  @tomkralidis If it's easy for you, can you answer the question on whether the failing test is the one mentioned?

**Comment by tomkralidis** [comment]
thanks @rjaduthie.  I'll chime in on the [CITE thread](http://lists.opengeospatial.org/pipermail/cite-forum/2017-December/001711.html).  Having said this setting up an instance for CITE is documented at https://github.com/geopython/pycsw/wiki/OGC-CITE-Compliance, feel free to ping in IRC to setup if you like.

**Comment by tomkralidis** [comment]
Below is CITE output of failing test against master with this PR's code changes:
```
Log for test s0061/d1447e6538_1/d1447e6423_1/d1447e2870_1

Test csw:csw-2.0.2-GetRecords-tc23.1 type Mandatory default result Passed (s0061/d1447e6538_1/d1447e6423_1/d1447e2870_1)

Assertion: 
      The response to a GetRecords request that specifies maxRecords=&quot;0&quot; must 
      not include any results.
    

Request d1447e6088_1:
   Method: POST
   URL: http://kralidis.ca:8000/
   Body: 
<csw:GetRecords xmlns="http://www.occamlab.com/ctl"
                xmlns:csw="http://www.opengis.net/cat/csw/2.0.2"
                xmlns:ctl="http://www.occamlab.com/ctl"
                xmlns:dc="http://purl.org/dc/elements/1.1/"
                xmlns:dct="http://purl.org/dc/terms/"
                xmlns:gen="java:com.occamlab.te.Generator"
                xmlns:gml="http://www.opengis.net/gml"
                xmlns:ogc="http://www.opengis.net/ogc"
                xmlns:ows="http://www.opengis.net/ows"
                xmlns:p="http://teamengine.sourceforge.net/parsers"
                xmlns:parsers="http://www.occamlab.com/te/parsers"
                xmlns:saxon="http://saxon.sf.net/"
                xmlns:te="http://www.occamlab.com/te"
                xmlns:tec="java:com.occamlab.te.TECore"
                xmlns:tems="java:com.occamlab.te.web.MonitorServlet"
                xmlns:xi="http://www.w3.org/2001/XInclude"
                xmlns:xlink="http://www.w3.org/1999/xlink"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                maxRecords="0"
                resultType="results"
                service="CSW"
                version="2.0.2">
   <csw:Query typeNames="csw:Record">
      <csw:ElementName>dc:identifier</csw:ElementName>
      <csw:ElementName>ows:BoundingBox</csw:ElementName>
      <csw:Constraint version="1.1.0">
         <ogc:Filter>
            <ogc:Not>
               <ogc:BBOX>
                  <ogc:PropertyName>ows:BoundingBox</ogc:PropertyName>
                  <gml:Envelope srsName="urn:x-ogc:def:crs:EPSG:6.11:4326">
                     <gml:lowerCorner>60.0 12.0</gml:lowerCorner>
                     <gml:upperCorner>70.0 20.0</gml:upperCorner>
                  </gml:Envelope>
               </ogc:BBOX>
            </ogc:Not>
         </ogc:Filter>
      </csw:Constraint>
   </csw:Query>
</csw:GetRecords>
   Response from parser p:XMLValidatingParser.CSW:
      <csw:GetRecordsResponse xmlns:csw="http://www.opengis.net/cat/csw/2.0.2"
                        xmlns:dc="http://purl.org/dc/elements/1.1/"
                        xmlns:dct="http://purl.org/dc/terms/"
                        xmlns:gmd="http://www.isotc211.org/2005/gmd"
                        xmlns:gml="http://www.opengis.net/gml"
                        xmlns:ows="http://www.opengis.net/ows"
                        xmlns:xs="http://www.w3.org/2001/XMLSchema"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        version="2.0.2"
                        xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2 http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd">
  <csw:SearchStatus timestamp="2017-12-14T19:24:09Z"/>
  <csw:SearchResults nextRecord="0" numberOfRecordsMatched="11" numberOfRecordsReturned="0"
                      recordSchema="http://www.opengis.net/cat/csw/2.0.2"/>
   <!--Response received in [482] milliseconds--></csw:GetRecordsResponse>

Message d1447e6175_1:
   [FAILURE] Expected csw:SearchResults/@nextRecord = 1.

Result: Failed
```

**Comment by tomkralidis** [comment]
Hi @rogie-bas: any (high level) summary/update on this one?

**Comment by rogie-bas** [comment]
ETS maintainer asserts that the behaviour when maxRecords=0 should be that nextRecord=1 (some lively debate being had!).  Possibly not going to be changed soon, so it might be prudent to alter merge request to comply with test for now, to fix the originally reported bug and still comply with the tests as they stand.

**Comment by tomkralidis** [comment]
Thanks @rogie-bas. Any chance you can update the PR accordingly?  We are looking to release a new version this week as part of the OSGeo code sprint in Bonn.

**Comment by rogie-bas** [comment]
I can have a go, earliest, tomorrow.  It might be only a case of rolling back the last commit, but it's been while, I'll have to spend a little time making sure of it.

**Comment by rogie-bas** [comment]
So, the PR now passes the CI tests with this repo, with the specification that nextrecord='1' for maxrecords='0' when using CSW2.  However, the CSW3 sets nextrecord to '0' in the same situation; this is to comply with the functionaltest in this repo, which has been in place for nearly two years.

If ets-csw202 changes to admit nextrecord='0' for maxrecords='0', then the CSW2 code can be changed to match CSW3; if it transpires that CSW3 should match the current ets-csw202, then the change can be with CSW3.  Apart from this, the code is very similar for the two files (pycsw/ogc/csw/csw2.py:880-891 & pycsw/ogc/csw/csw3.py:872-881).

**Comment by rogie-bas** [comment]
Let me know if you need me to do anything further.

I'll keep an eye on the ets-csw202 issue, but until we hear from Dirk or someone, I don't think there's going to be much change.

**Pull request merged**
