### PR TITLE
WIP: fix encoding for ISO output (#576)

### PR DESCRIPTION
**Pull request by tomkralidis**
# Overview
This PR attempts to fix the encoding issue for ISO output.
# Related Issue / Discussion
#576 
# Additional Information
NA
# Contributions and Licensing

(as per https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.
- [x] I have already previously agreed to the pycsw Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by DingDingFan0207** [comment]
Kia ora,

We are upgrading Geonode to meet python3 compatibility and ran into this bug here. Geonode has a dependency on pycsw, we are getting TypeErrors caused by the differences between byte literals and strings in Python3. Can we please have an update on the progress/problems here? We would be happy to help.

Dingding

**Comment by DingDingFan0207** [comment]
Hi @tomkralidis ,

As I mentioned before, our python3 upgrade of GeoNode is dependent on PyCSW, and this encoding problem is preventing us from passing tests under python3. Is a deadline/priority for this PR, again we are very keen on helping if necessary.

Kind Regards,
Dingding

**Comment by tomkralidis** [comment]
Can you provide a sample metadata record and environment / workflow so I can reproduce? Does this PR work for you?

**Comment by DingDingFan0207** [comment]
The latest change in this PR results in failure in Geonode's tests, however the commits that work with our upgradings are 

- 8739d56c67c5a70975de371c50e978b20572cbe6 [https://github.com/geopython/pycsw/blob/8739d56c67c5a70975de371c50e978b20572cbe6/pycsw/plugins/profiles/apiso/apiso.py#L389](url)

- 9f151040a99c1b32dbe02ce9ceabe0d62ea3b146 [https://github.com/geopython/pycsw/blob/9f151040a99c1b32dbe02ce9ceabe0d62ea3b146/pycsw/plugins/profiles/apiso/apiso.py#L389](url)

Regarding on the tests that fail in Geonode:
This cataloging code is used in Geonode many times, especially when running integration test with `TEST_RUN_INTERNAL_APPS=True python manage.py test geonode.geoserver.tests.test_server.SignalsTests.test_set_resources_links`, the test fails on [https://github.com/mtnorthcott/geonode/blob/py3/geonode/geoserver/tests) /test_server.py#L1141](url) with following messages:
```
File "geonode/geonode/geoserver/tests/test_server.py", line 1141, in test_set_resources_links
    self.assertTrue(count > 0, "No layers have got metadata")
AssertionError: False is not true : No layers have got metadata
```

**Comment by afabiani** [comment]
@tomkralidis @DingDingFan0207 just to add few more details on this, the error we get by using Python 3+ with pycsw is the following one:

```
Traceback (most recent call last):
  File "/home/alessio/Envs/geonode-3.0/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/alessio/Envs/geonode-3.0/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/alessio/Envs/geonode-3.0/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alessio/Envs/geonode-3.0/lib/python3.5/site-packages/django/views/decorators/clickjacking.py", line 50, in wrapped_view
    resp = view_func(*args, **kwargs)
  File "/mnt/d/work/code/python/geonode/geonode-2.10.x/geonode/catalogue/metadataxsl/views.py", line 52, in prefix_xsl_line
    raise err
  File "/mnt/d/work/code/python/geonode/geonode-2.10.x/geonode/catalogue/metadataxsl/views.py", line 46, in prefix_xsl_line
    record = catalogue.get_record(resource.uuid)
  File "/mnt/d/work/code/python/geonode/geonode-2.10.x/geonode/catalogue/backends/pycsw_local.py", line 74, in get_record
    results = self._csw_local_dispatch(identifier=uuid)
  File "/mnt/d/work/code/python/geonode/geonode-2.10.x/geonode/catalogue/backends/pycsw_local.py", line 165, in _csw_local_dispatch
    response = csw.dispatch()
  File "/home/alessio/Envs/geonode-3.0/lib/python3.5/site-packages/pycsw/server.py", line 561, in dispatch
    self.response = self.iface.getrecordbyid()
  File "/home/alessio/Envs/geonode-3.0/lib/python3.5/site-packages/pycsw/ogc/csw/csw2.py", line 1087, in getrecordbyid
    self.parent.kvp['outputschema'], self.parent.repository.queryables['_all']))
  File "/home/alessio/Envs/geonode-3.0/lib/python3.5/site-packages/pycsw/plugins/profiles/apiso/apiso.py", line 389, in write_record
    if caps is None and xml_blob is not None and xml_blob.startswith(b'<gmd:MD_Metadata'):
TypeError: startswith first arg must be str or a tuple of str, not bytes
```

It looks like the check is mixing string types and bytes.

**Comment by afabiani** [comment]
@tomkralidis by applying your patch I get this

```
Traceback (most recent call last):
  File "/home/alessio/Envs/geonode-3.0/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/alessio/Envs/geonode-3.0/lib/python3.5/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/alessio/Envs/geonode-3.0/lib/python3.5/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alessio/Envs/geonode-3.0/lib/python3.5/site-packages/django/views/decorators/clickjacking.py", line 50, in wrapped_view
    resp = view_func(*args, **kwargs)
  File "/mnt/d/work/code/python/geonode/geonode-2.10.x/geonode/catalogue/metadataxsl/views.py", line 52, in prefix_xsl_line
    raise err
  File "/mnt/d/work/code/python/geonode/geonode-2.10.x/geonode/catalogue/metadataxsl/views.py", line 46, in prefix_xsl_line
    record = catalogue.get_record(resource.uuid)
  File "/mnt/d/work/code/python/geonode/geonode-2.10.x/geonode/catalogue/backends/pycsw_local.py", line 74, in get_record
    results = self._csw_local_dispatch(identifier=uuid)
  File "/mnt/d/work/code/python/geonode/geonode-2.10.x/geonode/catalogue/backends/pycsw_local.py", line 165, in _csw_local_dispatch
    response = csw.dispatch()
  File "/home/alessio/Envs/geonode-3.0/lib/python3.5/site-packages/pycsw/server.py", line 561, in dispatch
    self.response = self.iface.getrecordbyid()
  File "/home/alessio/Envs/geonode-3.0/lib/python3.5/site-packages/pycsw/ogc/csw/csw2.py", line 1087, in getrecordbyid
    self.parent.kvp['outputschema'], self.parent.repository.queryables['_all']))
  File "/home/alessio/Envs/geonode-3.0/lib/python3.5/site-packages/pycsw/plugins/profiles/apiso/apiso.py", line 390, in write_record
    xml_blob_decoded = bytes.fromhex(xml_blob[2:]).decode('utf-8')
ValueError: non-hexadecimal number found in fromhex() arg at position 0
```

**Comment by tomkralidis** [comment]
Thanks @afabiani looks like this passes Travis.  Can you verify that I've applied your patch (see diff) correctly before I merge?

**Comment by kalxas** [comment]
We probably need to make a bug fix release after this gets merged.

**Comment by afabiani** [comment]
@tomkralidis I confirm the patch is correct. Thanks!

**Comment by afabiani** [comment]
@kalxas a bug fix version would be great so we can validate GeoNode tests on Travis too.

**Comment by kalxas** [comment]
We will coordinate a bug release soon.

**Comment by tomkralidis** [comment]
FYI as discussed 2.4.2 was released today.  Thanks @afabiani / @kalxas

**Comment by afabiani** [comment]
@tomkralidis wow, that's awesome. Thanks!

**Pull request merged**
