### PR TITLE
capture  concept-scheme structure in database field

### PR DESCRIPTION
**Pull request by pvgenuchten**
# Overview

Aim is to facilitate inclusion of themes in ogcapi-records

# Related Issue / Discussion

keywords are currently stored as a comman separated list without concept-scheme (thesaurus). 
Keeping keywords including their thesaurus enables filtering of keywords by concept schema

# Additional Information

image

# Contributions and Licensing

- [x] I have already previously agreed to the pycsw Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by kalxas** [comment]
We were considering changing the keyword column to JSON so that it can include the theme information. We had some issue with the OGC Cite testing when we tried this in the past. Perhaps adding themes in the model would be a better choice

**Comment by kalxas** [comment]
We should take into account this now: https://github.com/opengeospatial/ogcapi-records/issues/188

**Comment by kalxas** [comment]
and the specification pull request: https://github.com/opengeospatial/ogcapi-records/pull/190

**Review by kalxas — CHANGES_REQUESTED** [review]
Please review the new developments in OGC API Records

**Comment by tomkralidis** [comment]
+1.  TL;DR : `themes.concepts` is now a list of dicts, with each dict having `name` (required) and `url` (optional).  Example:

```json
        {
            "concepts": [
                {
                    "name": "atmosphericComposition",
                    "url": "https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_CategoryCode_atmosphericComposition"
                },
                {
                    "name": "pollution",
                    "url": "https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_CategoryCode_pollution"
                },
                {
                    "name": "observationPlatform",
                    "url": "https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_CategoryCode_observationPlatform"
                },
                {
                    "name": "rocketSounding",
                    "url": "https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_CategoryCode_rocketSounding"
                }
            ],
            "scheme": "https://wis.wmo.int/2012/codelists/WMOCodeLists.xml#WMO_CategoryCode"
        }
```

**Comment by kalxas** [comment]
Thank you Paul, we are going to verify the use of identification.keywords2 and keywords_object from OWSlib.

Good work!

**Review by kalxas — APPROVED** [review]

**Comment by kalxas** [comment]
@pvgenuchten can you please resolve the conflicts?

**Comment by pvgenuchten** [comment]
PR updated

**Pull request merged**
