### PR TITLE
pull

### PR DESCRIPTION
**Pull request by bukun**
# Overview
# Related Issue / Discussion
# Additional Information
# Contributions and Licensing

(as per https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst#contributions-and-licensing)
- [ ] I'd like to contribute [feature X|bugfix Y|docs|something else] to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.
- [ ] I have already previously agreed to the pycsw Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by tomkralidis** [comment]
@bukun thanks for the pull request.  Comments:
- remove all `.mo` files
- please acknowledge the Contributiong and Licensing section of your pull request.  In your case given this is your first pycsw contribution, you can check the first checkbox, and replace `[feature X|bugfix Y|docs|something else] ` with `documentation translations`

I'm +1 for merge once the above is addressed (we can squash and merge).  Thanks for this valuable contribution!

**Comment by tomkralidis** [comment]
@bukun can you redo/resubmit this pull request with only the relevant changes (docs).  This is a very valuable contribution -- thanks!

**Comment by bukun** [comment]
@tomkralidis 
Thanks.
I don't quit understand how to do.
However, I have put the translation for Chinnese to https://github.com/bukun/pycswcn .
And the chinese version of the docs have been published to  http://www.osgeo.cn/doc_pycsw/  .

**Comment by tomkralidis** [comment]
Hi @bukun I would suggest you re-fork and integrate your translations as follows:

- delete https://github.com/bukun/pycsw repository on GitHub
- fork again https://github.com/geopython/pycsw

```bash
git clone https://github.com/bukun/pycsw
cd pycsw
git branch zh-translations
git checkout zh-translations
cd docs/locale
mkdir -p zh/LC_MESSAGES
# copy all the .po files to zh/LC_MESSSAGES
git add zh
git commit -m 'add Chinese translations' zh
git push origin zh-translations
```

Then submit a GitHub pull request against https://github.com/bukun/pycsw/tree/zh-translations

**Comment by kalxas** [comment]
@tomkralidis +1

**Comment by ricardogsilva** [comment]
Hi @bukun 

I'm looking to clean up stale Pull Requests. What is your plan with this? As @tomkralidis stated this is a valuable contribution that we'd like to integrate into pycsw. However, in its current form that is not easy to do because the code has changed quite a lot since the original request.

@tomkralidis proposal that you refork and reintegrate the changes is the cleanest approach. Hope that you're up to it. In any case, this Pull Request should be closed, as it will not be merged in its current state. Hope to hear back from you.

Thanks a lot

**Comment by tomkralidis** [comment]
Sounds good @ricardogsilva. Should be doable though would be preferred if @bukun makes the fixes and updates.m the PR.

**Comment by kalxas** [comment]
Without an agreement to the contribution terms, we should not merge into our codebase...

**Comment by bukun** [comment]
Thanks for the comments. I would update the translation to the last of pycsw, and would try to merge the code into pycsw  repository. It is busy these days, may be at the end of 2016.

**Comment by bukun** [comment]
I have submitted a new pull request. https://github.com/geopython/pycsw/pull/493

I final find the problem.  The following line should add to conf.py, otherwise could not generate HTML in Chinese.

    locale_dirs = ['locale/'] # path is example but recommended.

**Comment by tomkralidis** [comment]
Closed in lieu of #493

**Pull request closed without merging**
