### PR TITLE
docker-alpine

### PR DESCRIPTION
**Pull request by epifanio**
# Overview
Update dockerfile to use latest alpine linux 3.11

# Related Issue / Discussion

# Additional Information

@aheimsbakk - I added you as contributors - if you agree, please review the licensing and copyrights checks :)

# Contributions and Licensing

(as per https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [x] I'd like to contribute [feature X|bugfix Y|docs|something else] to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.
- [x] I have already previously agreed to the pycsw Contributions and Licensing Guidelines

### CODE REVIEW

**Comment by tomkralidis** [comment]
Thanks @epifanio. @aheimsbakk  can you accept the below (checkboxes):

# Contributions and Licensing

(as per https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

- [ ] I'd like to contribute [feature X|bugfix Y|docs|something else] to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.
- [ ] I have already previously agreed to the pycsw Contributions and Licensing Guidelines

**Comment by aheimsbakk** [comment]
> Thanks @epifanio. @aheimsbakk can you accept the below (checkboxes):
> # Contributions and Licensing
> 
> (as per https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst#contributions-and-licensing)

 * [x]  I'd like to contribute [feature X|bugfix Y|docs|something else] to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.
 
* [x]  I have already previously agreed to the pycsw Contributions and Licensing Guidelines

**Comment by ricardogsilva** [comment]
@tomkralidis @epifanio 

I realize this has been merged already, but from taking a cursory look at the changeset, I see that some files are now dumped at the root of the image:

```sh
# build image
IMAGE_NAME=testing_pycsw
docker build -t ${IMAGE_NAME} -f Dockerfile .

# run a test container and check contents of '/'
docker run --rm -ti --entrypoint /bin/ash ${IMAGE_NAME} -c 'ls /'

MANIFEST.in  # this file is misplaced
README.rst  # this file is misplaced
VERSION.txt  # this file is misplaced
bin
build
dev
etc
home
lib
media
mnt
opt
proc
pycsw  # this file is misplaced
pycsw.egg-info  # this file is misplaced
requirements-dev.txt  # this file is misplaced
requirements-pg.txt  # this file is misplaced
requirements-standalone.txt  # this file is misplaced
requirements.txt  # this file is misplaced
root
run
sbin
setup.py  # this file is misplaced
srv
sys
tests  # this file is misplaced
tmp
usr
var
 
```

I also noticed that the new `Dockerfile` now includes bash, which seems unnecessary, since alpine's busybox comes with [ash].

[ash]: https://en.wikipedia.org/wiki/Almquist_shell

**Comment by tomkralidis** [comment]
Thanks @ricardogsilva.  I'll open another PR with some optimizations for review.

**Pull request merged**
